### ISSUE TITLE
Accept HTTP 301 as a valid page

### ISSUE THREAD

**Issue by mbdebian** [identifiers-org/cloud-ws-link-checker#15]
Modify the logic so HTTP 301 status codes are also accepted as a valid landing page.

**Comment by mbdebian** [comment]
I have updated the analysing strategy, it now accepts HTTP 301 as a valid destination.

Also, 3xx responses are being logged, to get some information on how providers use these HTTP status range.

**Comment by sarala** [comment]
Some of the scores are still not making sense for me. http://resolver.api.identifiers.org/pdb:4hhb Why is pdbsum's score 0?

**Comment by mbdebian** [comment]
On a quick check to the logs of the service when deployed the new version showed that some resources are sending HTTP 302 back (Found), so we may need to broader the acceptance of HTTP 3xx codes, that seem to be used insanely by providers… for God knows what…


--------
Manuel Bernal Llinares
mbdebian@gmail.com

**Comment by mbdebian** [comment]
This are the log entries that I was talking about:
2019-03-04 12:58:21.196  WARN 6 --- [       Thread-3] o.i.c.w.l.strategies.SimpleLinkChecker   : [HTTP 302] For URL https://www.ebi.ac.uk/pdbsum/2gc4
2019-03-04 12:58:21.196  INFO 6 --- [       Thread-3] o.i.c.w.linkchecker.daemons.LinkChecker  : Link Check result for URL 'https://www.ebi.ac.uk/pdbsum/2gc4', HTTP Status '302', assessment 'NOT OK'

I'm not saying it's a bad practice, it's just that we don't have the time or resources to do a full follow up to the end of the redirection chain, so we need to think how to address this "temporarily".

**Comment by mbdebian** [comment]
That URL redirects to https://www.ebi.ac.uk/thornton-srv/databases/cgi-bin/pdbsum/GetPage.pl?pdbcode=2gc4
So, we should think about following all redirects to the end of the chain, logging, somehow, the different URLs that were found on the way, and then evaluate the final URL.
This is something we need to evaluate before going for it, and it needs time and resources be assigned to it.
